In [1]:
!pip install tensorflow


[notice] A new release of pip is available: 25.2 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import tensorflow as tf
print(tf.__version__)

2.14.0


In [25]:
a = tf.constant([[1,2],[6,3]])
a

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [6, 3]])>

In [4]:
v = tf.Variable([[1,2],[6,3]])
v

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[1, 2],
       [6, 3]])>

In [10]:
c = tf.concat(values=[a,v], axis=1)
c

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[1, 2, 1, 2],
       [6, 3, 6, 3]])>

In [27]:
b = tf.zeros(shape=[3,4], dtype=tf.int32)
b

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])>

In [15]:
o = tf.ones(shape=[3,4], dtype=tf.int32)
o

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])>

In [29]:
r = tf.reshape(tensor = o, shape = [2,6]) #can put any number of rows and columns with 3x4 = 12 bytes
r

<tf.Tensor: shape=(2, 6), dtype=int32, numpy=
array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])>

In [31]:
t = tf.random.uniform(shape=[3,3], dtype=tf.float32)
t

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0.5914264 , 0.85942423, 0.8819282 ],
       [0.12493086, 0.97908807, 0.5706483 ],
       [0.1651063 , 0.07716286, 0.699239  ]], dtype=float32)>

In [22]:
d = tf.constant([[1.6,2.8],
                 [3.4,4.3],
                 [5.2,6.7],
                 [7.10,8.9]], tf.float32)
d_int = tf.cast(d, tf.int32)
print(d)
print(d_int)

tf.Tensor(
[[1.6 2.8]
 [3.4 4.3]
 [5.2 6.7]
 [7.1 8.9]], shape=(4, 2), dtype=float32)
tf.Tensor(
[[1 2]
 [3 4]
 [5 6]
 [7 8]], shape=(4, 2), dtype=int32)


In [33]:
t = tf.transpose(d)
t

<tf.Tensor: shape=(2, 4), dtype=float32, numpy=
array([[1.6, 3.4, 5.2, 7.1],
       [2.8, 4.3, 6.7, 8.9]], dtype=float32)>

In [36]:
mm = tf.matmul(c, d_int)
mm

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[26, 32],
       [66, 84]])>

In [39]:
m = tf.multiply(d_int, d_int)
m

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[ 1,  4],
       [ 9, 16],
       [25, 36],
       [49, 64]])>

In [40]:
f = tf.constant([[1,4],
                 [5,3],
                 [2,6],
                 [0,9]])
rows, columns = f.shape
print("R: ", rows, " C: ", columns) 

R:  4  C:  2


In [43]:
id= tf.eye(num_rows = 3, num_columns = 3, dtype=tf.int32)
id

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])>